baseURL: https://okitoxo.github.io/blog/
languageCode: es
defaultContentLanguage: es
title: Okito Blog
theme: papermod
languages:
  es:
    languageName: Español
    weight: 1
    menu:
      main:
        - name: Publicaciones
          url: posts/
          weight: 10
#   en:
#     languageName: English
#     menu:
#       main:
#         - name: Posts
#           url: posts/
#           weight: 10
params:
  description: Hablando del dia a dia de una persona involucrada en el arte y tecnologia.
  profileMode:
    enabled: false
    title: Okito Blog
    subtitle: Apasionado por el arte y la tecnologia.
    imageUrl: "/static/okito-logo.svg"
  socialIcons:
    - name: github
      url: https://github.com/okitoxo
    - name: rss
      url: index.xml
  homeInfoParams:
    title: Inspirar y crear
    content: >
      Este es un espacio para compartir mis errores y aprendizajes. Hablo de tecnologia,
      arte y mi corto tiempo de experiencias en este mundo.